apiVersion: v1
kind: ReplicationController
metadata:
  name: servicechain-backends
spec: 
  replicas: 8
  selector:
    layer: backend
    app: servicechain
  template:
    metadata:
      name: srvch-public
      labels:
        layer: backend
        app: servicechain
    spec:
      containers:
      - name: srvch-backend
        image: joffotron/backend:latest
        ports:
          - containerPort: 8000
                      
