apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  selector:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80 # the port that this service should serve on
    # the container on each pod to connect to, can be a name
    # (e.g. 'www') or a number (e.g. 80)
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx