kind: ReplicationController
apiVersion: v1
metadata:
  name: servicechain-v5
spec: 
  replicas: 4
  selector:
    layer: frontend
    app: servicechain
    version: v5
  template:
    metadata:
      name: srvch-public
      labels:
        layer: frontend
        app: servicechain
        version: v5
    spec:
      containers:
      - name: srvch-public
        image: joffotron/public:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: BACKEND_URL
            value: "http://svchn-backend-svc.default/"
          - name: DOGSTATSD_HOST_N_PORT
            value: "dogstatsd.default:8125"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          timeoutSeconds: 2   
