apiVersion: v1
kind: ReplicationController
metadata:
  name: servicechain
spec: 
  replicas: 2
  selector:
    layer: frontend
    app: servicechain
  template:
    metadata:
      name: srvch-public
      labels:
        layer: frontend
        app: servicechain
    spec:
      containers:
      - name: srvch-public
        image: joffotron/public:latest
        ports:
          - containerPort: 8080
        env:
          - name: BACKEND_URL
            value: "http://svchn-backend-svc.default/"
            