apiVersion: v1
kind: Service
metadata:
  name: test-health-elb
  labels: 
    app: servicechain
    layer: proxy
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    layer: frontend
    app: servicechain
  livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 2   
